// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AccordionController from "./accordion_controller"
application.register("accordion", AccordionController)

import CharterController from "./charter_controller"
application.register("charter", CharterController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import QuantityController from "./quantity_controller"
application.register("quantity", QuantityController)
